# Generated by Django 3.2.8 on 2021-10-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='disciunt',
            new_name='discount',
        ),
    ]
